version: '3'

services:
  proxy:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  webdav:
    image: bytemark/webdav
    hostname: webdav
    restart: always
    environment:
      AUTH_TYPE: Digest
      USERNAME: frodo
      PASSWORD: bolson
    volumes:
      - ./webdav:/var/lib/dav
    depends_on:
      - proxy
